name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Stap 1: Checkout repository
      - uses: actions/checkout@v3

      # Stap 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Stap 3: Installeer dependencies
      - name: Install Dependencies
        run: npm install

      # Stap 4: Bouw de Angular-app
      - name: Build Angular App
        run: npm run build:my-app

      # Stap 5: Deploy naar Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"                       # Specificeert dat de app moet worden geüpload
          app_location: "/"                      # Root van de monorepo
          output_location: "dist/apps/my-app"   # Map van de gebouwde app
          api_location: ""                      # Leeg laten als er geen API is
