# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy a Node.js app and an Angular app to an Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --prod

      - name: Zip artifacts for deployment
        run: |
          cd ${GITHUB_WORKSPACE}/dist/apps/data-api/ && zip -r ${GITHUB_WORKSPACE}/data-api-release.zip ./
          cd ${GITHUB_WORKSPACE}/dist/apps/my-app/ && zip -r ${GITHUB_WORKSPACE}/my-app-release.zip ./
          cd ${GITHUB_WORKSPACE}/dist/apps/rcmnd-api/ && zip -r ${GITHUB_WORKSPACE}/rcmnd-api-release.zip ./

      - name: Upload frontend-app artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: my-app-release.zip

      - name: Upload backend-api artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: data-api
          path: data-api-release.zip

      - name: Upload backend-rcmnd-api artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: rcmnd-api
          path: rcmnd-api-release.zip

  deploy-frontend-app:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: my-app

      - name: Unzip artifact for deployment
        run: unzip my-app-release.zip

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.BOOKAPIKEY }}
          app_location: "/"
          output_location: "dist/apps/my-app"

  deploy-backend-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: data-api

      - name: Unzip artifact for deployment
        run: unzip data-api-release.zip

      - name: Install dependencies
        run: npm install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'book-data-api'
          publish-profile: ${{ secrets.BOOK_DATA_API }}
          package: .

  deploy-backend-rcmnd-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: rcmnd-api

      - name: Unzip artifact for deployment
        run: unzip rcmnd-api-release.zip

      - name: Install dependencies
        run: npm install

      - name: Build the application (if needed)
        run: npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rcmnd-api-amin'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_RCMND }}
          package: .

      