name: Build and deploy Angular and NestJS apps to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Applications
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies and Build Apps
        run: |
          npm install
          npm run build --prod

      - name: Zip Artifacts for Deployment
        run: |
          cd ${GITHUB_WORKSPACE}/dist/apps/data-api && zip -r ${GITHUB_WORKSPACE}/data-api-release.zip .
          cd ${GITHUB_WORKSPACE}/dist/apps/my-app && zip -r ${GITHUB_WORKSPACE}/my-app-release.zip .

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: my-app-release.zip

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: data-api
          path: data-api-release.zip

  deploy-my-app:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy Angular App to Azure Static Web Apps
    steps:
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-app

      - name: Unzip Frontend Artifact
        run: unzip my-app-release.zip

      - name: Deploy Angular App to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_STONE_03E313603 }}
          app_location: "dist/apps/my-app" # Zorg ervoor dat dit pad correct is
          output_location: "" # Leeg laten, afhankelijk van jouw configuratie
          api_location: "" # Geen API in Static Web Apps

  deploy-data-api:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy NestJS Backend to Azure App Service
    steps:
      - name: Download Backend Artifact
        uses: actions/download-artifact@v3
        with:
          name: data-api

      - name: Unzip Backend Artifact
        run: unzip data-api-release.zip

      - name: Install Backend Dependencies
        run: npm install

      - name: Deploy NestJS Backend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'books-data-api' # Zorg dat dit overeenkomt met jouw App Service naam
          publish-profile: ${{ secrets.BACKEND_API }}
          package: .
