name: Build and deploy Angular Frontend and NestJS Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    name: Build and Deploy Angular Frontend
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Dependencies and Build Angular
        run: |
          npm install
          npm run build --prod
      - name: Deploy to Azure Static Web App
        id: deploy-to-frontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_STONE_03E313603 }}
          app_location: "/" # App source code path
          output_location: "dist/apps/my-app" # Built app content directory
          

  build-and-deploy-backend:
    runs-on: ubuntu-latest
    name: Build and Deploy NestJS Backend
    needs: build-and-deploy-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Dependencies and Build Backend
        run: |
          cd apps/data-api
          npm install
          npm run build
      - name: Zip Backend API Artifacts
        run: |
          cd dist/apps/data-api
          zip -r ../../../data-api-release.zip .
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'books-data-api' # Ensure this matches your App Service name
          publish-profile: ${{ secrets.BACKEND_API }}
          package: dist/apps/data-api
